WIP: ベンダーCSV読込
ogis-Yamada-Shizuka/denshow-quick pull request #12
Opened 2016-12-02 08:18 UTC by i-yamaguchi

2016-12-02 08:45 UTC, ryo-ryukalice requested changes

2016-12-02 08:45 UTC, ogihara-ryo commented on app/models/vendor.rb
> +      model = find_by_id(row['id']) || new
`find_or_initialize_by` という、こういう時のためのメソッドがあります。
Rails 本体の実装は下記の通りです。
```ruby
    def find_or_initialize_by(attributes, &block)
      find_by(attributes) || new(attributes, &block)
    end
```

ちなみに `find_by_属性名` のような動的なファインダーメソッドは非推奨とされているので、
`find_by` メソッドを使った方が良いです。
```ruby
find_by(id: row['id'])
```

今回はこれで
```ruby
model = find_or_initialize_by(id: row['id'])
```

2016-12-07 03:03 UTC, yamadashizuka commented
Sprint1 のスプリントレビューで、一覧から選ぶんじゃなくて自由に入力させる(文字種チェックのみする)ということになりました……ので、この変更要らなくなっちゃった気がします(汗)
文字種チェックは英大文字・数字のみ（記号はない）です。但し、小文字で入力した場合は登録時に自動で大文字にしてあげる(エラーにして直させるのではなく)という程度の親切はしてあげてほしいという。

2016-12-07 04:20 UTC, i-yamaguchi commented
>山田さん
ここ不要になっちゃいましたね。
このブランチはcloseしてvalidateと文字置換は[sp2-01]の時に対応したいと思います。

>荻原さん
レビューありがとうございます。気づくのが大分遅くなってしまいすみません。
指摘頂いたコードが他のところに実装されている部分あるのでリファクタリングしようと思います。
テストコード書かねばいけないですが、CSV読込みたいな時ってテスト用データはコードで書くorファイルを置くのどっちが良いのでしょうか？

参考：http://nextdeveloper.hatenablog.com/entry/2014/03/03/144342
コードで書くのもなかなか骨が折れそう…

2016-12-07 04:23 UTC, ogihara-ryo commented
> テストコード書かねばいけないですが、CSV読込みたいな時ってテスト用データはコードで書くorファイルを置くのどっちが良いのでしょうか？
ファイルで良いと思います。
必ずインポートに成功できるファイルを spec ディレクトリ内に置いておくのは悪くないです。
今、ちょうど同じような仕事をしているので、テストコードのサンプル(大したことないですが)を別途 slack で送りますね。

2016-12-07 07:27 UTC, closed without merging