vendor_codeのバリデート、大文字置換処理
ogis-Yamada-Shizuka/denshow-quick pull request #24
Opened 2016-12-12 10:54 UTC by i-yamaguchi

vendor_codeのバリデートは `文字入力は英大文字・数字のみ（記号はない）`

rspecでテストコード書くつもりがletの書き方でハマってしまったので、テストコード後から書きます。

2016-12-12 11:03 UTC, ogihara-ryo commented
どんな感じでハマってます？

2016-12-12 11:08 UTC, i-yamaguchi commented
関連したレコードを紐付けてあげたいんですが、
```
    let(:request_detail) { build(:request_detail) }
    let(:request_application) { build(:request_application) }
    let(:doc_type) { build(:doc_type) }
    let(:chg_type) { build(:chg_type) }
    request_detail.request_application_id = request_application.id
    request_detail.doc_type_id = doc_type.id
    request_detail.chg_type_id = chg_type.id
```
こんな感じで書くとエラー出ちゃう（letで書いた部分を変更しようとしてるからだと思いますが）ので、
factory_girlに渡す時に一緒に作らせよう！と思ったのですがちょっと時間かかりそうだったのでスキップしました…

2016-12-12 11:14 UTC, ogihara-ryo commented
今は一旦これぐらい冗長でも良いので、今テスト付属しておいたほうが良いかなー、と思います。
納期と工数次第ですが。
```ruby
let(:request_application) {
  build(
    :request_application,
    request_detail: [build(:request_detail, doc_type: build(:doc_type), chg_type: build(:chg_type))]
  )
}
```

2016-12-12 11:16 UTC, ogihara-ryo commented
ちなみに何のエラーが出ているかは分かりませんが、期待通りに関連付けできないのは
`build` しかしていないので、まだ ID が nil だからだと思います。

2016-12-12 11:18 UTC, i-yamaguchi commented
ありがとうございます。さっそく試してみます。
別件なんですが、validateに引っかかったattributeがどれか知りたい時は、
errorsにattributeのkeyが入っているか以外でスマートに知る方法ってあるんでしょうか？

イメージとしてはvalidateに引っかかったattributeの<td>部分だけ色を変えたいという感じです。

2016-12-12 11:21 UTC, ogihara-ryo commented
`errors.keys` で取るしかないと思いますねー、知っている限りでは。

2016-12-12 11:58 UTC, i-yamaguchi commented
factory部分は解決したのですがどの粒度でテスト書くか迷ってしまったので明日相談させて下さい:bow:

2016-12-13 06:21 UTC, i-yamaguchi commented
今からテストコード書きます！

2016-12-13 10:29 UTC, i-yamaguchi commented
なんやかんやでこんな時間になってしまいました…（実作業1Hほど）
```
・半角英字、半角数字、半角記号の入力が可能、かつ、
・英字は大文字のみ→システムで大文字に
・半角カナもOK
```
validateの仕様がこういう感じになっていたので、 `全角記号` はスルーしていたのですが、
よくよく考えたらダメだよねということで追加しています。

2016-12-13 10:36 UTC, ryo-ryukalice requested changes

2016-12-13 10:36 UTC, ogihara-ryo commented on spec/models/request_detail.rb
> +    INVALID_VALUES_TWO = %w(# ひらがな ｶﾀｶﾅ カタカナ 漢字 ！ Ａ １).freeze
これ、パターンを分けている理由は何ですか？
ちなみにコメントと `context` の文字列が1になってます。

2016-12-13 10:36 UTC, ogihara-ryo commented on spec/models/request_detail.rb
> +    describe 'doc_no validate' do
同じ spec 内なら、少し DRY を意識して保守性と可読性に倒しても良いかもしれません。
```ruby
%i(doc_no ........).each do |attribute| do
  describe"#{attribute} validate" do
    ...
        request_detail.write_attribute(attribute, valid_string)
    ...
  end
end
```

2016-12-13 10:36 UTC, ogihara-ryo commented on spec/factories/chg_type.rb
> +  factory :chg_type, class: ChgType do
`class` オプションは要らないと思います。

2016-12-13 10:48 UTC, i-yamaguchi commented on spec/models/request_detail.rb
> +    INVALID_VALUES_TWO = %w(# ひらがな ｶﾀｶﾅ カタカナ 漢字 ！ Ａ １).freeze
パターンを分けている理由はvendor_codeだけ入力チェックが違って
```
・ Vendorコードは存在チェックを行わない。文字入力は英大文字・数字のみ（記号はない）。
```
上記の仕様だからです。

>ちなみにコメントと context の文字列が1になってます。
修正します:bow:

2016-12-13 10:51 UTC, ogihara-ryo commented on spec/models/request_detail.rb
> +    INVALID_VALUES_TWO = %w(# ひらがな ｶﾀｶﾅ カタカナ 漢字 ！ Ａ １).freeze
じゃあ、その定数のスコープを `describe` で分けましょう。
vendor_code 以外でも _TWO の文字列を使いたいのであれば、
それらのスコープの定数配列にパターンを含めてください。

2016-12-13 10:52 UTC, i-yamaguchi commented on spec/models/request_detail.rb
> +    INVALID_VALUES_TWO = %w(# ひらがな ｶﾀｶﾅ カタカナ 漢字 ！ Ａ １).freeze
なるほど。
確かにそもそも同じdescribeに入れる必要もないですね。
ありがとうございます！

2016-12-13 10:57 UTC, i-yamaguchi commented on spec/models/request_detail.rb
> +    describe 'doc_no validate' do
```
%i(doc_no ........).each do |attribute|
  describe "#{attribute} validate" do
    VALID_VALUES_ONE.each do |valid_string|
      it do
        request_detail.write_attribute(attribute, valid_string)
        is_expected.to be_valid
      end
    end
  end
end
```
もうちょっと中身書くとこんな感じでしょうか？
昨日レビューで指摘あったところとおなじになりますが、
`valid_string` よりも `valid_value` の方がgood？

2016-12-13 11:00 UTC, ogihara-ryo commented on spec/models/request_detail.rb
> +    describe 'doc_no validate' do
そんな感じです！
別にそこのコンテキストは見透せる範囲だし、やりたいことも自明なので、
こういう時は `s` のような一文字変数でも良いと思います。

あと、無効な場合は、 `not_to be_valid` より `to be_invalid` の方が DSL っぽい気がします。

2016-12-13 11:04 UTC, i-yamaguchi commented on spec/models/request_detail.rb
> +    describe 'doc_no validate' do
このプロジェクトどんどんコードが書けるようになって（気のせいかもしれないですが）幸せすぎる…

2016-12-13 11:36 UTC, i-yamaguchi commented on spec/models/request_detail.rb
> +        # 有効な文字パターン1(半角英数、半角記号、半角カタカナ)
定数の部分もしかしたらレビューで指摘あった荻原さんのイメージと違うかもしれないです。
違ったらツッコミ頂けるとありがたいです。

2016-12-13 11:55 UTC, ogihara-ryo commented on spec/models/request_detail.rb
> +        # 有効な文字パターン1(半角英数、半角記号、半角カタカナ)
_ONE, _TWO というサフィックスはなくて良いと思います。コンテキストが違うので。

2016-12-14 08:36 UTC, ogihara-ryo commented on spec/models/request_detail.rb
> +        # 有効な文字パターン1(半角英数、半角記号、半角カタカナ)
コメントの「１」「２」も削除してくださいー。

2016-12-14 08:43 UTC, ryo-ryukalice approved these changes
🙆

2016-12-14 08:44 UTC, i-yamaguchi commented
ありがとうございます！
マージしますー

2016-12-14 08:44 UTC, merged