[sp2-01] エラーの表示とメッセージの日本語化
ogis-Yamada-Shizuka/denshow-quick pull request #25
Opened 2016-12-12 13:16 UTC by i-yamaguchi

`4つのエラーがあります〜` の部分に関してはscaffoldから移植しただけなので
文字を出さない or 日本語にする（内容考えないといけないですが）どちらかの対応かなと。
![fireshot capture 57 - denshowquick - http___localhost_3000_request_applications_import_excel](https://cloud.githubusercontent.com/assets/21189471/21100647/9c3ebcac-c0b8-11e6-9eee-e4f800a943e0.png)

2016-12-12 13:42 UTC, ryo-ryukalice requested changes

2016-12-12 13:42 UTC, ogihara-ryo commented on app/helpers/request_details_helper.rb
> +  def append_error_class(model, attirbute_sym)
`model` という名前はクラスを期待するのか、インスタンスを期待するのか分からないので、`object` 等の方が一般的です。
あと、ハンガリアンな記法は、動的型付けでダックタイピングを採用している Ruby の文化に合わないので止めましょう。

せっかくヘルパー化したなら `td` 要素ごとカプセル化して、変更に強くしておいても良いかもしれません。
ただ、DOM の面倒を Helper で見過ぎ感もあるのでお好みで。。
```ruby
def render_table_data(object, attribute_name, value)
  content_tag(:td, value, class: object.errors.key?(attirbute_name) ? 'alert-danger' : nil )
end
```

2016-12-12 13:51 UTC, ryo-ryukalice requested changes

2016-12-12 13:51 UTC, ogihara-ryo commented on config/locales/models/request_application/ja.yml
> +  activerecord:
`ja.activerecord` の下に、下記みたいな感じで追加しておいて、
```yml
template:
  header: "{{count}}件のエラーがあります。"
```

scaffold が生成した View 部分のこれを
```erb
<h2><%= pluralize(@request_application.errors.count, "error") %> prohibited this request application from being saved:</h2>
```

こうすれば良いかなと。
```erb
<h2><%= t('activerecord.errors.template.header', count: @request_application.errors.length) %></h2>
```

2016-12-12 13:52 UTC, ogihara-ryo commented
こいつルーティング push してます？
`registration_result_request_application_path`

2016-12-13 00:59 UTC, i-yamaguchi commented on app/helpers/request_details_helper.rb
> +  def append_error_class(model, attirbute_sym)
ありがとうございます！
カプセル化せずにただclassのstringを返す現状のままでも良いかなと。
もうちょっと色々しないといけなくなったらカプセル化してしまおうと思います。

2016-12-13 01:01 UTC, i-yamaguchi commented
```
  resources :request_applications do
    collection { post :import_excel }
    member { get :registration_result } ←これとはまた別ですかね？
    resources :request_details
  end
```

2016-12-13 01:02 UTC, i-yamaguchi commented on config/locales/models/request_application/ja.yml
> +  activerecord:
さっそくそうします！

2016-12-13 01:07 UTC, ogihara-ryo commented
ああ、すみません。デフォルトブランチが master なのか。大丈夫です！

2016-12-14 08:45 UTC, ryo-ryukalice approved these changes
🙆

2016-12-14 08:47 UTC, i-yamaguchi commented on app/models/request_detail.rb
> +  # TODO: rspecセットアップ後にvalidateのテストコードを書くこと
コメントが復活している…！

2016-12-14 08:48 UTC, i-yamaguchi commented
マージしまっす！

2016-12-14 08:49 UTC, merged