[sp2-02] request_applicationの機種コードと技術資料番号をCSV出力
ogis-Yamada-Shizuka/denshow-quick pull request #26
Opened 2016-12-15 03:22 UTC by i-yamaguchi

2016-12-15 03:26 UTC, i-yamaguchi commented on config/routes.rb
> +  namespace :request_applications do
セルフコメント：
この部分もっと違う書き方あるかもしれません。

2016-12-15 03:49 UTC, ryo-ryukalice requested changes

2016-12-15 03:49 UTC, ogihara-ryo commented on app/models/request_application_export_csv.rb
> +            csv << values
ローカル変数のキャッシュに意味がなければ、直接代入しましょう。
C 等では1ステートメントに1作用、と言ったりしますが、LL (特に Ruby) では
よりコンパクトで可読性の高いコードの方がスタンダードだと思います。

2016-12-15 03:49 UTC, ogihara-ryo commented on app/models/request_application_export_csv.rb
> +      csv_data.encode(Encoding::SJIS)
ここも `csv_data` といった曖昧な名前のローカル変数を作るより、メソッドチェインの方が良いと思います。
```ruby
CSV.generate { |csv|
  ...
}.encode(Encoding::SJIS)
```

2016-12-15 03:49 UTC, ogihara-ryo commented on config/routes.rb
> +  namespace :request_applications do
URL に `csv_export` を挟みたくないですねー。。
`/request_applications/search` `/request_applications/export` の方が良いかなと。
`search` は別で使うかもしれないし、 `export` も PDF とか他フォーマットができるかもしれないので。

こんな感じでいけませんか？
`::CsvExportController` を見てしまうかも。。？
```ruby
namespace :request_applications do
  collection do
    get :search, to: 'csv_export#search'
    get :export, to: 'csv_export#export'
  end
end
```

2016-12-15 03:49 UTC, ogihara-ryo commented on config/routes.rb
> +  namespace :request_applications do
ちなみに L12 に `namespace :request_applications` ブロックはあります。

2016-12-15 04:32 UTC, i-yamaguchi commented on config/routes.rb
> +  namespace :request_applications do
今コントローラ名は複数形にしているのですが、  
この場合複数形の `exports` ではなく `出力する` という意味で `export` の方が好ましいですか？

2016-12-15 04:41 UTC, i-yamaguchi commented on app/models/request_application_export_csv.rb
> +      csv_data.encode(Encoding::SJIS)
メソッドチェインしようと `{ }` の形式にするとrubocopが複数行の時は `do end` にしてね。って言ってきますが今回はコメントして無視する方向でOKですか？

2016-12-15 04:42 UTC, ogihara-ryo commented on app/models/request_application_export_csv.rb
> +      csv_data.encode(Encoding::SJIS)
メソッドチェインする場合は言ってこないと思いますが、言ってきてますか？
だとしたら rubocop のバグ。。

2016-12-15 04:46 UTC, i-yamaguchi commented on app/models/request_application_export_csv.rb
> +      csv_data.encode(Encoding::SJIS)
書き方の問題なんでしょうか…？
```
def export(request_applications)
      CSV.generate { |csv|
        csv << %w(機種コード 技術資料番号)
        collect_values(request_applications).each { |value| csv << value }
      }.encode(Encoding::SJIS)
    end
```
こんな感じで書いてきます。
※重複削除する部分作りたかったので `request_applications` のeachの部分切り出しました。

2016-12-15 05:11 UTC, i-yamaguchi commented on config/routes.rb
> +  namespace :request_applications do
単数にするとコントローラとして読込できなくなった（なぜ…）のでこのままでいこうと思います。

2016-12-15 05:13 UTC, ryo-ryukalice commented on config/routes.rb
> +  namespace :request_applications do
あ、見逃してました。単数系で良いです。
Controller として認識されないのは、ファイル名を変えていないからじゃないですか？

2016-12-15 06:14 UTC, i-yamaguchi commented on config/routes.rb
> +  namespace :request_applications do
キャッシュが残っていたのか謎ですが、PC再起動したらちゃんと認識してくれるようになりました。

2016-12-15 06:26 UTC, ryo-ryukalice requested changes

2016-12-15 06:26 UTC, ogihara-ryo commented on app/models/request_application_export_csv.rb
> +    # メソッドチェインするとrubocopエラーが出る(バグ？)ので無効化
すみません、rubocop の実装見たら、普通に期待通りの動作でした。
普段 `BlockDelimiters` を exclude しているので気付きませんでした。。
規約は規約なので、 do..end にして `end.encode` にしましょう。

2016-12-15 06:31 UTC, ogihara-ryo commented on app/models/request_application_export_csv.rb
> +          values << [request_application.model.code, detail.doc_no]
N + 1 起こってないですか？

2016-12-15 06:33 UTC, i-yamaguchi commented on app/models/request_application_export_csv.rb
> +          values << [request_application.model.code, detail.doc_no]
完全にeager_loadさせるの忘れてましたね。
この場合、コールする側からeager_loadしたインスタンスを渡す、でOKです？
それともコールする側は深いこと考えなくていいに従ってこっちでするべきなんでしょうか？

2016-12-15 06:34 UTC, ogihara-ryo commented on app/models/request_application_export_csv.rb
> +          values << [request_application.model.code, detail.doc_no]
こっちでいいですよ。

2016-12-15 09:20 UTC, ryo-ryukalice requested changes

2016-12-15 09:20 UTC, ogihara-ryo commented on app/views/request_applications/csv_export/search.html.erb
> +  <% end %>
ここら辺インデント見直してください。

2016-12-15 09:20 UTC, ogihara-ryo commented on app/views/request_applications/csv_export/search.html.erb
> +            <td><%= check_box_tag 'request_application[ids][]', request_application.id, false, id: "#{request_application.id}" %></td>
明示的なID属性指定が必要ですか？
もし必要であれば、数字だけの ID は良くないので、何かプレフィックスを付ける等してください。

2016-12-16 01:36 UTC, ryo-ryukalice approved these changes
🙆

2016-12-16 01:37 UTC, i-yamaguchi commented
マージしますー

2016-12-16 01:37 UTC, merged