山田さんに指摘頂いたバグを修正
ogis-Yamada-Shizuka/denshow-quick pull request #29
Opened 2016-12-16 09:21 UTC by i-yamaguchi

修正した内容は
```
・エクセル読込時に存在しない値を読むと 'import failed' になる
・projectが存在しない時にshowを表示すると落ちる
・New Request Applicationの要求日と入手希望日の「月」の表示がおかしい
```
上記３点です。

2016-12-16 09:24 UTC, yamadashizuka commented
ありがとうございますー！ いちおう、こっちで確認してみますね！

2016-12-16 09:53 UTC, yamadashizuka commented
>・エクセル読込時に存在しない値を読むと 'import failed' になる
>　⇒ なおってない……？
　　　⇒ なおってました！

>・New Request Applicationの要求日と入手希望日の「月」の表示がおかしい
>　⇒ なおってない……？
　　　⇒ なおってました！

2016-12-19 00:42 UTC, ryo-ryukalice requested changes

2016-12-19 00:42 UTC, ogihara-ryo commented on app/controllers/request_applications_controller.rb
>      redirect_to request_applications_path, notice: 'import failed.'
今回の改修部分じゃなくてアレなんですが、フラッシュのキーは `alert` が良いですね。

2016-12-19 00:42 UTC, ogihara-ryo commented on app/controllers/request_applications_controller.rb
> +    initialize_flow
`build` して初期化メソッドを呼ぶのではなく、
Flow クラス側のイニシャライザー(文字通り `initialize` メソッド)で行ってください。

2016-12-19 00:42 UTC, ogihara-ryo commented on app/controllers/request_applications_controller.rb
> +    initialize_flow
また、そこはモデルのテストを書いてください。
( `build` した時に、各種属性に期待の値が詰まっていること)

2016-12-19 06:09 UTC, ryo-ryukalice commented on app/models/request_application_import_excel.rb
> +    # ぼっち演算子を書くとなぜかrubocop errorになるのでdisable
手元で動かした感じ、このコメント外してもパスするんですが、
rubocop のバージョンが古いとかないですか？
もし、どうしても出るならエラーメッセージを見せてください。

2016-12-19 06:31 UTC, i-yamaguchi commented on app/models/request_application_import_excel.rb
> +    # ぼっち演算子を書くとなぜかrubocop errorになるのでdisable
もしかしたらatomの `linter-rubocop` のバグかもしれないです。
ちょっと手動rubocopしてみます。

2016-12-19 06:35 UTC, i-yamaguchi commented on app/models/request_application_import_excel.rb
> +    # ぼっち演算子を書くとなぜかrubocop errorになるのでdisable
```
app/models/request_application_import_excel.rb:57:75: E: unexpected token error
(Using Ruby 2.1 parser; configure using TargetRubyVersion parameter, under AllCops)
      attributes[:model_id] = Model.find_by(code: attributes[:model_code])&.id
```

エラー内容ちゃんと見たら原因書いてありました。
`(Using Ruby 2.1 parser; configure using TargetRubyVersion parameter, under AllCops)`
ということなので設定しておこうと思います。

2016-12-19 06:43 UTC, ogihara-ryo commented on app/models/request_application_import_excel.rb
> +    # ぼっち演算子を書くとなぜかrubocop errorになるのでdisable
Gemfile 見てくれないのかな。。.ruby_version は見てくれるみたいなんですが。
まあ、とりあえずは TargetRubyVersion 追加で良いです。

2016-12-19 06:47 UTC, i-yamaguchi commented on app/models/request_application_import_excel.rb
> +    # ぼっち演算子を書くとなぜかrubocop errorになるのでdisable
targetを2.3にしたらrubocopに文字列リテラルがfreezeされてないと言われるようになったので、  
(ruby 3.0に合わせた対応っぽいですが)
```
Style/FrozenStringLiteralComment:
  Enabled: false
```
上記でrubocopエラーを外したいと思うのですが、良いですかね？
ここは山田さんとも要相談だとは思いますが。

2016-12-19 07:00 UTC, ogihara-ryo commented on app/models/request_application_import_excel.rb
> +    # ぼっち演算子を書くとなぜかrubocop errorになるのでdisable
私は外して良いと思います。

2016-12-19 08:35 UTC, i-yamaguchi commented on app/controllers/request_applications_controller.rb
>      redirect_to request_applications_path, notice: 'import failed.'
ここは別ブランチで対応しまっす

2016-12-19 08:38 UTC, ogihara-ryo commented on app/models/flow.rb
> +  def set_flow_order
普通の `initialize` じゃダメですかね？

2016-12-19 08:45 UTC, ryo-ryukalice requested changes

2016-12-19 08:45 UTC, ogihara-ryo commented on spec/models/flow.rb
> +    context 'initialize時にhistory_noに 1 が設定される' do
`context` は、条件の場合分け時に使います。
この場合は、 `it` に与えれば良いです。
`initialize時に` という言葉も `describe` と重複して冗長なので切りましょう。

```ruby
it 'history_noに 1 が設定されること' do
  expect(flow.history_no).to eq 1
end
```

2016-12-19 08:45 UTC, ogihara-ryo commented on spec/models/flow.rb
> +      it do
こういう時が `context` の使いどころです。

```ruby
context 'flow_orderが複数存在する場合' do
  it 'orderの降順で設定されること' do
  end
end

2016-12-19 08:46 UTC, i-yamaguchi commented on spec/models/flow.rb
> +    context 'initialize時にhistory_noに 1 が設定される' do
　なるほど

2016-12-19 08:50 UTC, i-yamaguchi commented on app/models/flow.rb
> +  def set_flow_order
コールバックがあるので `activerecord` 的に `after_initialize` 推奨なのかと勝手に思ってました。
多分普通の `initialize` で問題ないはず？
その場合
```
def initialize
  return if persisted?
  set attribute...
end
```
みたいな感じでしょうか？

2016-12-19 08:55 UTC, ogihara-ryo commented on app/models/flow.rb
> +  def set_flow_order
というか、 `initialize` と `after_initialize` コールバックでは呼ばれる条件が違います。
(これは Rails が悪い)
`initialize` なら、 `new_record?` は見なくていいはず。(一応確認して頂いた方が良いかも)

2016-12-19 09:00 UTC, i-yamaguchi commented on app/models/flow.rb
> +  def set_flow_order
了解しましたー

2016-12-19 09:14 UTC, i-yamaguchi commented on spec/models/flow.rb
> +      it do
contextは `〜の場合`（まさに場合分け）に使うってことですね。やっと分かってきた感じ

2016-12-19 10:59 UTC, ogihara-ryo commented on app/models/flow.rb
> +  def initialize(*)
'(*)` とは？

2016-12-19 11:00 UTC, ogihara-ryo commented on app/models/flow.rb
> +  def initialize(*)
`(*)` とは？

2016-12-19 11:05 UTC, i-yamaguchi commented on app/models/flow.rb
> +  def initialize(*)
完全にやらかしてますね。
正しくは `*args` ですね。
blockもあるかもしれないのでちょっとgithub見て確認してみます。

2016-12-19 11:23 UTC, i-yamaguchi commented on app/models/flow.rb
> +  def initialize(*)
`ActiveRecord::Base` が `ActiveRecord::Core` を `include` しているので下記URLの部分かと思うんですが、

https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/core.rb#L272
```
def initialize(attributes = nil, options = {})
      ...
end
```
なので正しくは `(attributes = nil, options = {})` みたいですね。
そもそも `initialize` で引数設定する必要なかったり…？

2016-12-19 12:23 UTC, ryo-ryukalice commented on app/models/flow.rb
> +  def initialize(*)
> そもそも initialize で引数設定する必要なかったり…？

new の引数が `initialize` のパラメーターになるので、引数を設定する必要はあります。

2016-12-19 12:59 UTC, ryo-ryukalice requested changes

2016-12-19 12:59 UTC, ogihara-ryo commented on spec/models/flow.rb
> +        create(:flow_order, dept: create(:dept, name: '技術情報課'), order: 1)
ここは `before` ブロックで設定しましょうか。
```ruby
context 'flow_orderが複数存在する場合' do
  before do
    flow_order.update(order: 2)
    create(:flow_order, dept: create(:dept, name: '技術情報課'), order: 1)
  end

  it 'orderの降順で設定されること' do
    expect(build(:flow).dept.name).to eq '技術情報課'
  end
end
```

2016-12-19 13:03 UTC, i-yamaguchi commented on app/models/flow.rb
> +  def initialize(*)
`Model.new(attribute)` したときに値設定できなかったので間違ってなくて良かったです:ok_woman:

2016-12-20 00:49 UTC, ryo-ryukalice approved these changes

2016-12-20 01:33 UTC, i-yamaguchi commented
マージしますー

2016-12-20 01:33 UTC, merged