WIP:[sp1-01] #TK-01078 request_detailとprojectのmodel定義
ogis-Yamada-Shizuka/denshow-quick pull request #3
Opened 2016-11-24 07:21 UTC by i-yamaguchi

2016-11-24 07:52 UTC, ryo-ryukalice requested changes

2016-11-24 07:52 UTC, ogihara-ryo commented on app/models/request_application.rb
> +  has_many :request_details, dependent: :destroy
`@request_application.request_details` だと少し冗長なので、 `@request_application.details` でアクセスできた方が良いかなー。。

2016-11-24 07:58 UTC, i-yamaguchi commented on app/models/request_application.rb
> +  has_many :request_details, dependent: :destroy
了解しました

2016-11-24 08:02 UTC, ryo-ryukalice approved these changes
🙆 
(バージョン管理において、修正がレビューの指摘によるものかはどうでも良いので、
  コミットメッセージは改修の内容を説明するものが望ましいです。)

2016-11-25 01:23 UTC, yamadashizuka commented
コレってマージしちゃってOKですよね。(ＷＩＰついてないし←今回は確認した！)

2016-11-25 02:08 UTC, ogihara-ryo commented
[WIP] 付いてなくて、私が approve したものは、merge しちゃって大丈夫です！

2016-11-25 02:09 UTC, yamadashizuka commented
らじゃーですー！ やります。

2016-11-25 02:09 UTC, merged