WIP: [sp2-03] #TK-01106 tsvファイルを読込後登録する(1パターン)
ogis-Yamada-Shizuka/denshow-quick pull request #30
Opened 2016-12-19 10:40 UTC by i-yamaguchi

2016-12-19 13:05 UTC, ryo-ryukalice requested changes

2016-12-19 13:05 UTC, ogihara-ryo commented on app/controllers/for_matching_datas/csv_import_controller.rb
> +    for_matching_datas.each(&:save)
`ForMatchingDataImportCsv.import` で `save` しない理由は何かありますか？
また、バリデーションエラーが検出できなさそうですが、 `save!` にしなくて良いですか？
そして、 `transaction` で失敗した場合にロールバックさせる必要はありませんか？
(途中まで半端に登録されて良いのか)

2016-12-19 13:05 UTC, ogihara-ryo commented on app/views/layouts/application.html.erb
> +  <span> <%= link_to t('.for_matching_datas_import_csv'), for_matching_datas_import_path %></span>　｜　
`<span>` の後の半角スペース、後ろにはないのに統一感がないので、
元々だとは思いますが、ここで直しておいてください。

2016-12-19 13:07 UTC, i-yamaguchi commented on app/views/layouts/application.html.erb
> +  <span> <%= link_to t('.for_matching_datas_import_csv'), for_matching_datas_import_path %></span>　｜　
了解です。確かに統一感ないですね。

2016-12-19 13:13 UTC, i-yamaguchi commented on app/controllers/for_matching_datas/csv_import_controller.rb
> +    for_matching_datas.each(&:save)
> ForMatchingDataImportCsv.import で save しない理由は何かありますか？
今のところ特に無いです。
ただ今後どのレコードがダメだったか知りたいかなーと思ったのでこうしてみました。
YAGNI的には不要だし `ForMatchingDataImportCsv.import` でsaveしまっす。

> transaction で失敗した場合にロールバックさせる必要はありませんか？
関連性がある訳ではないの不要ですが `transaction do` で作ったほうがDB的に良いと思うので作り変えちゃいます。

2016-12-20 00:44 UTC, ryo-ryukalice approved these changes

2016-12-20 01:34 UTC, merged