modelのimportメソッドをリファクタリング
ogis-Yamada-Shizuka/denshow-quick pull request #38
Opened 2016-12-22 13:09 UTC by i-yamaguchi

2016-12-22 13:13 UTC, ryo-ryukalice approved these changes
見違えるほど、いいコードです！🙆

2016-12-22 13:16 UTC, i-yamaguchi commented on spec/models/model.rb
> +    it '読み込んだCSVと登録された件数が同一である' do
件数が同一かのテストで `Model.all.size` は適切じゃないかも？
（rspecの書き方によって左右されないかちょっと心配）

2016-12-22 13:17 UTC, i-yamaguchi commented
自分より早く荻原さんに見てもらっていたという…
ありがとうございます！

2016-12-22 13:19 UTC, ogihara-ryo commented on spec/models/model.rb
> +    it '読み込んだCSVと登録された件数が同一である' do
であれば、 `change` マッチャーを使いましょう。
```ruby
expect { subject }.to change { Model.count }.by csv_values
```
みたいな感じです。

2016-12-22 13:21 UTC, i-yamaguchi commented on spec/models/model.rb
> +    it '読み込んだCSVと登録された件数が同一である' do
なるほど。そんなものが。
ありがとうございます！

2016-12-22 13:36 UTC, ryo-ryukalice requested changes

2016-12-22 13:36 UTC, ogihara-ryo commented on spec/models/model.rb
> +      Model.all.each_with_index do |record, i|
念のため、こっちも同じように考慮しておきましょう。
```ruby
Model.order(:id)[-csv_values.count..-1].each_with_index do |record, i|
```

2016-12-22 13:38 UTC, ogihara-ryo commented on spec/models/model.rb
> +      Model.all.each_with_index do |record, i|
僕も最近知ったのですが、 `.all` の順番は RDBMS 等のように環境によって左右されるので、
明示的に `order(:id)` すると良いです。

2016-12-22 13:42 UTC, i-yamaguchi commented on spec/models/model.rb
> +      Model.all.each_with_index do |record, i|
なるほど。
少し別の話になるんですが、rubyって同じ処理（厳密には同じでない場合ありますが）のエイリアスが複数ありますが、
荻原さん的には `size` `length` `count` だと一番よく使われますか？

2016-12-22 13:43 UTC, ogihara-ryo commented on spec/models/model.rb
> +      Model.all.each_with_index do |record, i|
名前の通りです。
サイズなら `size` 、 長さなら `length` 、数なら `count` です。そのためのエイリアスなので。

2016-12-22 13:46 UTC, i-yamaguchi commented on spec/models/model.rb
> +      Model.all.each_with_index do |record, i|
たしかに。ちょっと感動(?)

2016-12-22 14:00 UTC, i-yamaguchi commented on spec/models/model.rb
> +      Model.all.each_with_index do |record, i|
```
      Model.order(:id)[-csv_values.count..-1].each_with_index do |record, i|
        expect(record.code).to eq csv_values[i]
      end
```
なぜかこのコードだと `subject` が実行されないみたいでテストが通らない…
ちょっとここの部分は月曜に回しますー

2016-12-26 02:17 UTC, i-yamaguchi commented on spec/models/model.rb
> +      Model.all.each_with_index do |record, i|
なぜかもなにも `subject` も結局 `let` って事を忘れておりました。
上のコードだとsubjectが実行されないのも当たり前な訳で…ハズカシー。

ということで `before` ブロックに入れてしまおうと思います。

2016-12-26 02:26 UTC, i-yamaguchi commented on spec/models/model.rb
> +      subject
`before` で呼ぶと `読み込んだCSVと登録された件数が同一である` でも行われてしまって意図した動きにならないので、
`it` の中で呼ぶようにしてみました。 
いや、そういうのは望ましくない。っていう事であれば火曜日にでも指摘お願いしますー

2016-12-26 02:30 UTC, ryo-ryukalice requested changes

2016-12-26 02:30 UTC, ogihara-ryo commented on spec/models/model.rb
> +    end
テストが書きにくいということは、テストの目的や種類が異なるということなので、
`describe` を分けてしまいましょう。

```ruby
    describe '登録件数の確認' do
      it { expect { Model.import(file) }.to change { Model.count }.by csv_values.length }
    end

    describe '登録内容の確認' do
      before { Model.import(file) }
      it do
        Model.order(:id)[-csv_values.count..-1].each_with_index do |record, i|
          expect(record.code).to eq csv_values[i]
        end
      end
    end
```

2016-12-27 04:40 UTC, ryo-ryukalice requested changes

2016-12-27 04:40 UTC, ogihara-ryo commented on spec/models/model.rb
> +    subject { Model.import(file) }
ここから下消し忘れです！

2016-12-27 04:42 UTC, ogihara-ryo commented on spec/models/model.rb
> +    subject { Model.import(file) }
ん？なんか push ミス？

2016-12-27 04:43 UTC, i-yamaguchi commented on spec/models/model.rb
> +    subject { Model.import(file) }
ファイル名が `model.rb` とかだったので `model_spec.rb` に変更したんですがなんかうまくいってなかった模様。

2016-12-27 04:45 UTC, ryo-ryukalice approved these changes
🙆

2016-12-27 04:45 UTC, i-yamaguchi commented
ファイル名が `model.rb` とかだったので、 `model_spec.rb` に変更したのがうまくいってなかったみたいなので何回もpushしちゃいました。
お騒がせしました。

2016-12-27 04:46 UTC, merged