WIP:[sp1-01] #TK-01079 request_applicationのcontrollerとviewを編集
ogis-Yamada-Shizuka/denshow-quick pull request #4
Opened 2016-11-25 06:44 UTC by i-yamaguchi

2016-11-25 07:23 UTC, i-yamaguchi commented
![fireshot capture 45 - denshowquick - http___localhost_3000_request_applications_4_edit](https://cloud.githubusercontent.com/assets/21189471/20617293/78664d26-b32b-11e6-9c66-d98733ea4288.png)
暫定の画面イメージ

2016-11-25 07:31 UTC, ryo-ryukalice requested changes

2016-11-25 07:31 UTC, ogihara-ryo commented on app/views/request_applications/_form.html.erb
> +          <% @request_application.details.all.each do |detail| %>
`all` は不要です。

2016-11-25 07:31 UTC, ogihara-ryo commented on app/views/request_applications/_form.html.erb
> +          <% next if detail.object.id.present? %>
保存済みのレコードを弾いて、 `new_record` のみ引っ張りたいなら
```ruby
next if detail.object.persisted?
```

2016-11-25 07:31 UTC, ogihara-ryo commented on app/views/request_applications/_form.html.erb
> +      <%= f.submit 'Save and End Regist', class:"btn btn-primary", data: { action: 'end_regist'} %>
L146, L147 のハッシュブレースの末尾の半角スペース忘れ

2016-11-25 07:34 UTC, i-yamaguchi commented on app/views/request_applications/_form.html.erb
> +          <% @request_application.details.all.each do |detail| %>
allしないとbuildしたとき等の空の時にeachが回って空のtdが出来てしまうので、やむを得ずallしてます。

2016-11-25 07:39 UTC, ogihara-ryo commented on app/views/request_applications/_form.html.erb
> +          <% @request_application.details.all.each do |detail| %>
であれば、それをコードに語らせると良いです。
```ruby
@request_application.details.select(&:persisted?).each do |detail|
```

2016-11-25 07:43 UTC, ryo-ryukalice approved these changes
🙆

2016-11-25 07:55 UTC, yamadashizuka commented
画面イメージありがとうございますー。
はい、こんな感じでとりあえず良いと思います。
若干悩めるのは、今回は無関係の項目(Emargencyとか)ですが、まぁ今sprintではとりあえず放置ってことでいいかなーと。動作上なんか困ることあれば対処って程度で。

2016-11-25 07:57 UTC, ogihara-ryo commented
あ、まだ WIP か。。すみません。。

2016-11-25 08:02 UTC, i-yamaguchi commented
show以外は変更加えたのでコードに問題なければ一旦ここでマージして頂ければと思います。
メソッド名が微妙なのとcontrollerがsuper fatなのでやばいです…

2016-11-25 08:11 UTC, ryo-ryukalice requested changes

2016-11-25 08:11 UTC, ogihara-ryo commented on app/controllers/request_applications_controller.rb
> +  def detail_params_key_arr
型を表すより、複数形にしてコレクションあることだけを表した方が良いです。
`detail_params_keys`

2016-11-25 08:11 UTC, ogihara-ryo commented on app/controllers/request_applications_controller.rb
> +      redirect_to edit_request_application_path(id: @request_application.id), notice: redirect_notice_message
```ruby
redirect_to edit_request_application_path(@request_application), notice: redirect_notice_message
```

2016-11-25 08:11 UTC, ogihara-ryo commented on app/controllers/request_applications_controller.rb
> +      redirect_to @request_application
ここはフラッシュメッセージ不要なのですか？

2016-11-25 08:12 UTC, i-yamaguchi commented on app/controllers/request_applications_controller.rb
> +      redirect_to @request_application
メッセージ入れ忘れですね。

2016-11-25 08:12 UTC, ogihara-ryo commented
@yamadashizuka 
これ、更新の時も続けて登録するような要望があるのですかね？
create 時は連続登録はよくある UI なので分かるんですが、
update 時にも連続登録って必要ですか？

2016-11-25 08:19 UTC, yamadashizuka commented
Update時の連続登録っていうのは、request_detail のUpdate時って意味ですか？
そうであれば、それは要らないと思っています。

request_application を登録するときに、それに紐づくrequest_detailを連続登録したい(コレを、「create 時は連続登録」って仰ってるんですよね？)はアリだと思っていますが、request_detail修正は、1個づつでいいかなぁと思います。

2016-11-25 08:21 UTC, yamadashizuka commented
あ。
request_application と n個の request_detail を登録した後、(いったん一覧に戻るとかして)もういちど request_detail を連続登録したいってことはあるんじゃないかなと思っていますけど……。

2016-11-25 08:47 UTC, ogihara-ryo commented
ちょっと今画面を動かして見せてもらったのですが、
ちょっと request_application と request_details の submit 方法がカオスで
URI も RESTful じゃなくてダブルカオスだったので、
瞬殺であれば修正をお願いしました。

2016-11-25 08:47 UTC, yamadashizuka commented
了解ですー。こちらも今ちょっと矢田さんと打ち合わせ中なので、急がなくても大丈夫です。
＃むしろ残業にならないようにしてくださいま(涙)

2016-11-25 08:48 UTC, yamadashizuka commented
なんか、目の前で矢田さんが「全部投げ捨ててくれた方がいいと思います(泣)」と言ってます。

2016-11-25 08:50 UTC, i-yamaguchi commented
>＃むしろ残業にならないようにしてくださいま(涙)
お気遣いありがとうございます。
そんなに悩まずにできるはずなので修正しますー

>なんか、目の前で矢田さんが「全部投げ捨ててくれた方がいいと思います(泣)」と言ってます。
既存部分があるとイメージしやすくて作りやすいので大分助かってます！

2016-11-28 08:34 UTC, i-yamaguchi commented
![fireshot capture 46 - denshowquick - http___localhost_3000_request_applications_new](https://cloud.githubusercontent.com/assets/21189471/20661162/a1b7af8c-b590-11e6-8c0f-08401632d49b.png)
requset application new

![fireshot capture 47 - denshowquick - http___localhost_3000_request_details_new_id 17](https://cloud.githubusercontent.com/assets/21189471/20661172/af6fe388-b590-11e6-947f-afda14f72f75.png)
request application detail

まとめて作業ができずに細切れになってしまったので時間かかってしまいましたが、
一旦上記画像でこのタスクは終了したいと思います。

2016-11-28 08:44 UTC, ryo-ryukalice requested changes

2016-11-28 08:44 UTC, ogihara-ryo commented on app/controllers/request_applications_controller.rb
> +      redirect_to new_request_detail_path(id: @request_application.id), notice: redirect_notice_message
インスタンスを渡すだけで飛べませんか？
```ruby
redirect_to new_request_detail_path @request_application, notice: redirect_notice_message
```

2016-11-28 08:44 UTC, ogihara-ryo commented on app/views/request_applications/edit.html.erb
> +      <%= render partial: 'shared/request_application_form', locals: { f: f } %>
`_form` のサフィックスが付いた部分テンプレートの割に `form` 要素は外にありますが、
`form_for` ヘルパーまで部分テンプレート内に入れると使い回しの面から不都合がありますか？

2016-11-28 08:44 UTC, ogihara-ryo commented on app/views/request_applications/edit.html.erb
> +<% unless @request_application.close %>
boolean の属性は `?` 付きのメソッドが作られるので、より明示的に尋ねることができます。
`@request_application.close?`

2016-11-28 08:45 UTC, yamadashizuka commented
画面イメージ貼り付けありがとうございます！
こちらでもコードもってきてちょこっと動かしてみました。動作については、なるほどです。
ちょっと(2015年度版のカオスとの兼ね合いもあり)画面遷移をどうするかが要検討だなーと思いますが、それはコレとは違いますし、いったんココでこのタスクを閉じるのは賛成です。
＃何はともあれやりたいことはできる訳だし！
ということで、動きに関しては現時点ではコレで良いと思いました。

2016-11-28 08:48 UTC, i-yamaguchi commented on app/controllers/request_applications_controller.rb
> +      redirect_to new_request_detail_path(id: @request_application.id), notice: redirect_notice_message
確認しますー

2016-11-28 08:49 UTC, i-yamaguchi commented on app/views/request_applications/edit.html.erb
> +      <%= render partial: 'shared/request_application_form', locals: { f: f } %>
今思えば特に外に追い出す必要あまり感じないですね。
修正します！

2016-11-28 08:53 UTC, ogihara-ryo commented on app/views/request_applications/edit.html.erb
> +      <%= render partial: 'shared/request_application_form', locals: { f: f } %>
はい、submit の内容が変わるので Controller と Action の名前から分岐すれば良いです。
ただ、それらをやると余計に複雑になるのであれば、
`_request_application_form.html.erb` ではなく `_request_application_attributes.html.erb` 等に
リネームすれば良いです。

2016-11-28 08:54 UTC, i-yamaguchi commented on app/views/request_applications/edit.html.erb
> +      <%= render partial: 'shared/request_application_form', locals: { f: f } %>
すみませんよくよく思えばnewとeditで表示するボタンをview側でif使わずに変えたいと思ってこうしたんでした。
なにか良い方策ありますかね？

2016-11-28 08:58 UTC, ogihara-ryo commented on app/views/request_applications/edit.html.erb
> +      <%= render partial: 'shared/request_application_form', locals: { f: f } %>
erb 内で `action_name == 'new'` しても良いと思いますよ。
form オブジェクトを引数に取るヘルパーを作るのも少し辛いですし、
この規模で独自 FormBuilder 作るのもやりすぎ感あるので。

2016-11-28 08:59 UTC, ogihara-ryo commented on app/views/request_applications/edit.html.erb
> +      <%= render partial: 'shared/request_application_form', locals: { f: f } %>
部分テンプレートの名前を変える側に倒しても、全然アリだと思います。

2016-11-28 09:06 UTC, i-yamaguchi commented on app/controllers/request_applications_controller.rb
> +      redirect_to new_request_detail_path(id: @request_application.id), notice: redirect_notice_message
インスタンスを渡すと paramsの中身が form: `id` になるのですが、
request_details_controllerのnew側で
```
@request_application = RequestApplication.find(params[:id])
```
こういう感じで入れるようにしているので、そもそもこの入れ方がまずいですかね？

2016-11-28 09:08 UTC, i-yamaguchi commented on app/views/request_applications/edit.html.erb
> +      <%= render partial: 'shared/request_application_form', locals: { f: f } %>
detail側でも使っていて中身で分岐するとややこしくなりそうなので、
テンプレートの名前を変える方向でいきたいと思います。

2016-11-28 09:10 UTC, ogihara-ryo commented on app/controllers/request_applications_controller.rb
> +      redirect_to new_request_detail_path(id: @request_application.id), notice: redirect_notice_message
ああ、ルーティングが入れ子になってないんですね。
```ruby
resouces :request_application do
  resources: request_details
end
```
とすべき設計ではないですか？

2016-11-28 09:19 UTC, i-yamaguchi commented on app/controllers/request_applications_controller.rb
> +      redirect_to new_request_detail_path(id: @request_application.id), notice: redirect_notice_message
たしかにそうですね。
入れ子にします！

2016-11-28 09:40 UTC, ryo-ryukalice requested changes

2016-11-28 09:40 UTC, ogihara-ryo commented on app/views/shared/_application_details_table.html.erb
> +          <th></th>
もう一個空の th 要素がないとデザイン崩れませんか？
線が細くなったりなど。

2016-11-28 09:45 UTC, ogihara-ryo commented on app/views/request_details/new.html.erb
> +  <%= render partial: 'shared/application_detail_form', locals: { f: f } %>
ここのリネームもお願いします
(すみません、多分これで最後です！)

2016-11-28 09:47 UTC, i-yamaguchi commented on app/views/request_details/new.html.erb
> +  <%= render partial: 'shared/application_detail_form', locals: { f: f } %>
ハッ！一緒に変更すればよかったですね。気が利かずすみません！

2016-11-28 09:51 UTC, ryo-ryukalice approved these changes
🙆 
お疲れ様でした！

2016-11-28 09:55 UTC, yamadashizuka commented
(途中でお二方の遣り取りから振り落とされてましたが(汗))OKってことなので、マージしますねー。

2016-11-28 09:56 UTC, merged