WIP: [sp3-01] #TK-01124 matcher class 作成・処理実装
ogis-Yamada-Shizuka/denshow-quick pull request #50
Opened 2017-01-16 10:08 UTC by i-yamaguchi

2017-01-16 10:12 UTC, i-yamaguchi commented on config/routes.rb
>        get :matching_result, to: 'request_applications/matching#matching_result'
セルフコメント：
`matching_result` アクションに関しては、 期待する `request_application` が単数の為、`member` に変更。

2017-01-16 10:12 UTC, i-yamaguchi commented on app/models/request_application_matcher.rb
> +class RequestApplicationMatcher
`class` 名がちょっとイマイチな感じです。

2017-01-17 09:30 UTC, i-yamaguchi commented
こんな感じの画面出力になります。

![_1017](https://cloud.githubusercontent.com/assets/21189471/22014869/f306fd60-dce2-11e6-941e-1c610389adde.png)

2017-01-18 05:35 UTC, ryo-ryukalice requested changes

2017-01-18 05:35 UTC, ogihara-ryo commented on app/models/request_application_matcher.rb
> +class RequestApplicationMatcher
やっぱり、 `RequestApplication` クラスに Mix-in させるモジュールにしましょう。
`@request_application.compare_to_matching_datas` みたいにアクセスできるように。

2017-01-18 06:43 UTC, ogihara-ryo commented on app/models/request_application_matcher.rb
> +class RequestApplicationMatcher
これを `RequestApplication` クラスに Mix-in してください。
書き殴っただけなので、シンタックスエラーとかあると思うので、よしなにお願いします。
あと bullet で適切に n + 1 を検出して対策してください。
```
module RequestApplication::Matcher
  def compare_to_matching_datas
    @for_matching_datas = ForMatchingData.where(model_code: model.code).order(doc_no: :ASC)
    details.includes(:doc_type, :chg_type).flat_map { |detail| compare_to detail }
  end

  private

  def compare_to(detail)
    key = "#{model.code} #{doc_no}"
    if @for_matching_datas.all? { |for_matching_data| detail[:doc_no] != for_matching_data[:doc_no] }
      return { key: key, match: false, detail: detail_values_for_display(request_detail) }
    end

    @for_matching_datas.map do |for_matching_data|
      if convert_detail_attribute_names(request_detail) == convert_for_matching_data_attribute_names(for_matching_data)
        { key: key, match: true, detail: detail_values_for_display(detail), for_matching_data: for_matching_data.document_no }
      else
        { key: key, match: false, for_matching_data: for_matching_data.document_no }
      end
    end
  end

  def detail_values_for_display(detail)
    # TODO: doc_typeにもとづいて並び順を変更する必要有るか要検討
    convert_detail_attribute_names(detail).values.compact.unshift(@request_application.model.code).join('|')
  end

  def convert_detail_attribute_names(detail)
    {
      doc_no: detail.doc_no
      doc_type: detail.doc_type.name
      sht: detail.sht
      rev: detail.rev
      eo_chgno: detail.eo_chgno
      chg_type: detail.chg_type&.name
      mcl: detail.mcl
      scp_for_smpl: detail.scp_for_smpl
      scml_ln: detail.scml_ln
    }
  end

  def convert_for_matching_data_attribute_names(for_matching_data)
    {
      doc_no: for_matching_data.doc_no
      doc_type: for_matching_data.doc_type_str
      sht: for_matching_data.sht
      rev: for_matching_data.revision
      eo_chgno: for_matching_data.eo_chgno
      chg_type: for_matching_data.chg_type_str
      mcl: for_matching_data.mcl
      scp_for_smpl: for_matching_data.scp_for_smpl
      scml_ln: for_matching_data.scml
    }
  end
end
```

2017-01-18 10:34 UTC, i-yamaguchi commented on app/helpers/request_applications_helper.rb
> +  # TODO: 一致・不一致の部分をymlに定義する
この部分は `helper` に分けずに `view` に記述する。

2017-01-19 00:25 UTC, i-yamaguchi commented on app/models/request_application/matcher.rb
> +    details.includes(:doc_type, :chg_type).order(doc_no: :ASC).flat_map { |detail| compare_to detail }
ブロック内だと
```
compare_to(detail)
```
みたいに `()` をつけない方が良いんですかね？

2017-01-19 00:25 UTC, i-yamaguchi commented on app/models/request_application/matcher.rb
> +    @for_matching_datas.select { |r| r if r.doc_no == detail.doc_no }.map do |for_matching_data|
```
select { |r| r if r.doc_no == detail.doc_no }
```
もっと分かりやすく `doc_no` が同一の `for_matching_data` を比較するようにした方が良い？

2017-01-19 00:25 UTC, i-yamaguchi commented on app/models/request_application/matcher.rb
> +    convert_detail_attribute_names(detail).values.delete_if(&:blank?).unshift(model.code).join('|')
`nil` だけではなく `空文字` が `attribute` の値として存在する場合があるので、
```
values.compact
を
values.delete_if(&:blank?)
```
に変更しましたが、もっと良い書き方もありそう。

2017-01-19 00:25 UTC, i-yamaguchi commented on app/controllers/request_applications/matching_controller.rb
> +    @matching_results = @request_application.compare_to_matching_datas
view側で下記のように比較処理を行うのは適切ではないと思ったので、
```
@request_application.compare_to_matching_datas.each do ~~
```
コントローラ側で `@matching_results` に値を詰めてます。

2017-01-19 01:38 UTC, ogihara-ryo commented on app/models/request_application/matcher.rb
> +    details.includes(:doc_type, :chg_type).order(doc_no: :ASC).flat_map { |detail| compare_to detail }
あまり深く考えてないですが、宣言的にっていうか英語的にっていうか。。
そんな感じに書きたい時に括弧を省略してます。

2017-01-19 01:41 UTC, ogihara-ryo commented on app/models/request_application/matcher.rb
> +    @for_matching_datas.select { |r| r if r.doc_no == detail.doc_no }.map do |for_matching_data|
あ、すみません。
この方法で良いですが、 `select` はブロックの評価値を見るので、下記で良いです。
```ruby
select { |r| r.doc_no == detail.doc_no }
```
ちなみに `r` ってなんですか？

2017-01-19 01:41 UTC, ogihara-ryo commented on app/models/request_application/matcher.rb
> +    convert_detail_attribute_names(detail).values.delete_if(&:blank?).unshift(model.code).join('|')
これで良いと思いますー。

2017-01-19 01:48 UTC, ryo-ryukalice requested changes

2017-01-19 01:48 UTC, ogihara-ryo commented on app/views/request_applications/matching/matching_result.html.erb
> +            <td class="<%= 'unmatch-color' unless result[:match] %>">
クラス名には、ビジュアルがどう変化するのかではなく、そのドキュメントの意味を与えてください。
例えば、赤字でなく bold にする、という要求があってもドキュメントには影響がないように。
`unmatch` だけでも良いと思います。

2017-01-19 02:09 UTC, i-yamaguchi commented on app/models/request_application/matcher.rb
> +    @for_matching_datas.select { |r| r if r.doc_no == detail.doc_no }.map do |for_matching_data|
```
@for_matching_datas.select { |for_matching_data| for_matching_data.doc_no == detail.doc_no }.map do |for_matching_data|
```
ってすると頻繁に `for_matching_data` が出てきて冗長かなと思ったので、  
`record` の `r` が良いかなと思ったのですがイケてなかったですね。

2017-01-19 02:11 UTC, ogihara-ryo commented on app/models/request_application/matcher.rb
> +    @for_matching_datas.select { |r| r if r.doc_no == detail.doc_no }.map do |for_matching_data|
スコープがごく短いので1文字なのは問題ないですが record の r はちょっと分かり難いので
f とか fmd とかにしましょうか。

2017-01-19 04:31 UTC, ryo-ryukalice approved these changes
🙆

2017-01-19 09:22 UTC, i-yamaguchi commented
特に問題なさそうなのでマージします！

2017-01-19 09:23 UTC, merged