[sp3-02] #TK-01128 機種コードセレクトボックス絞込機能
ogis-Yamada-Shizuka/denshow-quick pull request #51
Opened 2017-01-19 09:18 UTC by i-yamaguchi

こんな感じでセレクトボックスの内容の絞込ができます。

![default](https://cloud.githubusercontent.com/assets/21189471/22100492/326ac5ae-de73-11e6-991c-6191f6f21330.png) 

B画面にbootstrapが当たっていなかったのでついでにあてました。※画像参照

やっぱり機種コードはコードの昇順になっていた方が使い易いような気がしますね。
とりあえずそのままにしてあります。

今回の要望は `CHG TYPE` と `DOC TYPE` はありませんでしたがここも同様にしたほうが良さそうです。

2017-01-19 09:26 UTC, i-yamaguchi commented
既知の不具合として、`select2` の要素に
・`input-sm` とかが容易に当てられない
があります。
出来ないことはなさそうなんですが時間かかりそうだったのでデフォルトのサイズにしています。
（なのでちょっとその部分だけ太ってます）

2017-01-19 09:27 UTC, ryo-ryukalice requested changes

2017-01-19 09:27 UTC, ogihara-ryo commented on app/views/request_applications/_search.html.erb
> +          <%= f.collection_select :model_id_eq, Model.all, :id, :code, {include_blank: true },  class: "form-control input-sm select-model"  %>
ついでにこの括弧直しといてください。

2017-01-19 09:38 UTC, ryo-ryukalice approved these changes
🙆

2017-01-19 10:25 UTC, yamadashizuka commented
おお〜。
#部分一致で出る感じ？

確かに、コード昇順ソートは欲しい気がしますね。

2017-01-19 10:26 UTC, i-yamaguchi commented
部分一致で出ますね。

昇順ソートはこのブランチマージされたら入れますね。

2017-01-20 00:23 UTC, i-yamaguchi commented
動きを見て頂けたみたいなので、マージします

2017-01-20 00:24 UTC, merged