#TK-01133 未選択時にエラーメッセージを表示
ogis-Yamada-Shizuka/denshow-quick pull request #58
Opened 2017-01-23 05:05 UTC by i-yamaguchi

I画面(K-PEACEデータ取得用CSV出力)で出力対象を選択せずに出力ボタンを押すと落ちるのを修正。
![default](https://cloud.githubusercontent.com/assets/21189471/22192168/fc8fed2e-e174-11e6-9765-3250a23f9192.png)

2017-01-23 05:09 UTC, i-yamaguchi commented on app/views/request_applications/csv_export/search.html.erb
> +<% if alert.present? %>
`notice` や `alert` の記述が色々なところに散らばってきたので
どこかでまとめないといけないですね。

`shared` にメッセージ表示のテンプレートを作ったほうが良さそう？

もしくは、タイトルの上部に表示されても良いのであれば `application.html` に記述するか。

2017-01-23 05:09 UTC, i-yamaguchi commented on config/locales/ja.yml
> +  controller:
ここちょっと冗長すぎるかもしれません。
適当な場所が思い浮かばず。

2017-01-23 05:11 UTC, ryo-ryukalice requested changes

2017-01-23 05:11 UTC, ogihara-ryo commented on app/views/request_applications/csv_export/search.html.erb
> +<% end %>
layout ファイルに移動するか、位置が悪ければ (見出しが先に必要等)  `ApplicationHelper` に切り出しましょう。

2017-01-23 05:19 UTC, ogihara-ryo commented on config/locales/ja.yml
> +  controller:
冗長なのはともかく、キーから要求元整理番号のファイルであることが特定できないのが問題ですね。
エクスポートファイルが増えた時、困ると思います。
`ja` 直下に `error_xxx_is_not_selected` みたいなキーでも充分な気がしますけどねー。。

2017-01-24 00:52 UTC, i-yamaguchi commented on app/views/layouts/application.html.erb
> +        <p class="alert alert-danger"><%= alert.html_safe %></p>
```
<p class="alert alert-danger"><%= alert.html_safe %></p>
```
改行が入った文字列が `alert` として渡される場合があるので `html_safe` しています。
そもそも `alert` に値を詰める側が考慮すべき事なのかもしれませんが…

2017-01-24 02:20 UTC, ryo-ryukalice approved these changes
とりあえずOKです🙆

2017-01-24 06:04 UTC, i-yamaguchi commented
マージしますー

2017-01-24 06:04 UTC, merged