WIP: [sp4-01] #TK-01153 現在の技術資料要求書一覧を旧画面として退避
ogis-Yamada-Shizuka/denshow-quick pull request #72
Opened 2017-02-01 10:01 UTC by i-yamaguchi

現在の画面を変更する前に、旧画面として退避させました。
対象は index, show, 進捗状況等の変更部分です。
退避させなかったその他の部分はリンクならリンク先を `#` に、
ボタンなら `disable` にしてます。

2017-02-01 10:06 UTC, i-yamaguchi commented
To:荻原氏
コントローラのテストを書こうと思いますが、
迷走してしまったのでどこかで相談させて下さいー

2017-02-02 10:18 UTC, i-yamaguchi commented on spec/controller/older_request_applications_spec.rb
> +  describe 'OlderRequestApplicationsController test' do
とりあえず迷走したなりにテストを書いてみたので、
金曜日にレビューお願いします！

2017-02-02 10:31 UTC, ogihara-ryo commented on spec/controller/older_request_applications_spec.rb
> +  describe 'OlderRequestApplicationsController test' do
実装と同じことをしてはテストの意味がないのですが、
今回の件は200が返ることだけを見れば充分だと思います。

画面の正常性を保証するのではなく、
画面が生きてられることだけを保証しておこう、
あるいは生きていられなくなったことを検知できるようにしておこう、
という意味でリクエストのテストをお願いした次第でした。
言葉足らずですみません。

2017-02-02 10:49 UTC, i-yamaguchi commented on spec/controller/older_request_applications_spec.rb
> +  describe 'OlderRequestApplicationsController test' do
>実装と同じことをしてはテストの意味がないのですが、
たしかに…！
ちゃんと確認せずにとりあえず作ってしまう私がそもそも良くないので、
明日ちょっとだけ確認させてください！

2017-02-03 05:20 UTC, ryo-ryukalice requested changes

2017-02-03 05:20 UTC, ogihara-ryo commented on spec/controller/older_request_applications_spec.rb
> +  describe 'OlderRequestApplicationsController test' do
このブロックは L3 と重複しているので外に出してください。

2017-02-03 05:23 UTC, ryo-ryukalice requested changes

2017-02-03 05:23 UTC, ogihara-ryo commented on app/controllers/older_request_applications/request_applications_controller.rb
> +  # TODO: ファイル読込に失敗したのか、フォーマットが違うのかをexceptionで判定する
処理される予定がないのに note コマンドに引っかかると鬱陶しいので、
`TODO:` 以外の文字列で表現してください。

2017-02-03 05:25 UTC, ryo-ryukalice requested changes

2017-02-03 05:25 UTC, ogihara-ryo commented on app/controllers/older_request_applications/request_applications_controller.rb
> +  # 関連する Model 等が変更された場合の動作は保証せず。
この下で rubocop も無効化しておきましょう。

2017-02-03 06:53 UTC, ryo-ryukalice approved these changes
rubocop、enable しなくてもファイルを跨いで設定が引き継がれたりしなかったですよね。。？
🙆

2017-02-03 07:03 UTC, i-yamaguchi commented
>rubocop、enable しなくてもファイルを跨いで設定が引き継がれたりしなかったですよね。。？
なんかちょっと怪しい気がしてきたので確認します。

2017-02-03 07:13 UTC, i-yamaguchi commented on app/controllers/older_request_applications/request_applications_controller.rb
> +# rubocop:disable all
他のファイルはちゃんとチェックされるっぽいです。
`Class has too many lines.` で怒られてたのでコメント位置ずらしました。

2017-02-03 07:14 UTC, ryo-ryukalice approved these changes

2017-02-03 07:18 UTC, merged