[sp4-02] Ｌ画面(リコンサイル結果)画面関係の要望対応
ogis-Yamada-Shizuka/denshow-quick pull request #82
Opened 2017-02-08 00:42 UTC by i-yamaguchi

・要求書側項目の値が違っていた場合は文字を赤く
・項目ブランク不一致は「？」に置換
・要求書詳細の編集画面へのリンクを設置
・再実行ボタンの設置

リンクの部分ですがPO要望の「要求書の文字をリンク」にするではなく、
ボタンを置いてみようという方向になってましたが、
行に編集ボタンが出たり出なかったりで使いづらい感じになってしまったので、リンクに戻してます。

画面的にはこんな感じです。
![2017-02-08 9 36 12](https://cloud.githubusercontent.com/assets/21189471/22718285/df594c62-ede2-11e6-9935-00bb47dba4e9.png)

2017-02-08 11:25 UTC, i-yamaguchi reviewed
セルフコメント

2017-02-08 11:25 UTC, i-yamaguchi commented on app/models/request_application/matcher.rb
>  module RequestApplication::Matcher
気になるポイント：
`request_application` moduleとして扱うのがちょっと苦しくなってきた感があるかなと。
`compare_to_matching_datas` メソッドがviewの表示の為だけなので一致してない感が。

2017-02-08 11:25 UTC, i-yamaguchi commented on app/models/request_application/matcher.rb
> +  def compare_for_view(doc_no)
気になるポイント：
メソッド名がおかしい気がする。

2017-02-08 11:25 UTC, i-yamaguchi commented on app/models/request_application/matcher.rb
> +  def convert_to_display_value(value)
気になるポイント：
このメソッドでHTMLタグを書き込んで viewで `html_safe` して表示している。
view_helper でも表示用にあれこれしているのでいっその事なら `<tr>` を全てここで作ったほうが良かった？

2017-02-08 11:25 UTC, i-yamaguchi commented on app/models/request_detail.rb
> +  def compare_attributes
解説：
for_matching_dataとの比較用にメソッドを生やした。
以前は `module` 内にあったが、オブジェクト指向的にこっちの方が自然かなと思ったので。

2017-02-08 11:25 UTC, i-yamaguchi commented on app/models/request_application/matcher.rb
> +          results << { key: key, match: true, detail: display_values(detail.compare_attributes), for_matching_data: display_values(for_matching_data.compare_attributes), detail_id: detail.id }
気になるポイント：
view側でリンクを生成する為に下記コード書いてますが、ちょっと他のやり方のほうが良かったかも。
```
detail_id: detail.id
```

2017-02-08 11:25 UTC, i-yamaguchi commented on app/models/request_application/matcher.rb
> +  def replace_diffrent_attribute_value(attributes, unmatched_for_matching_datas)
解説：
このメソッドで要求書(detail) と K-PEACE側の項目の不一致部分を確認。

2017-02-08 11:53 UTC, ryo-ryukalice requested changes
matcher.rb は明日見ます！

2017-02-08 11:53 UTC, ogihara-ryo commented on app/helpers/request_details_helper.rb
> +  end
1度しか呼ばれていなさそうですが、ヘルパー化の意味はありますか？
あるとすれば、シグネチャーを少しいじって、こんな感じにしましょう。
```ruby
def link_to_edit_detail_path(name, detail)
  return if name.blank?
  link_to name, edit_request_application_request_detail_path(detail.request_application, detail), class: 'edit-link'
end
```

2017-02-08 11:53 UTC, ogihara-ryo commented on app/models/request_detail.rb
> +  def compare_attributes
やるなら `RequestDetail::Matcher` モジュールを作って Mix-in ですが、
今回は `RequestApplication::Matcher` 内のままでも良いかな、と思います。
マッチング処理はとにかく追い出したいです。

2017-02-08 11:54 UTC, ogihara-ryo commented on app/models/request_detail.rb
> +  def compare_attributes
と思ったけど、 `ForMatchingData` とダックタイピングしたい感じになってそうなので
(まだ matcher.rb 読んでないけど。。)
Mix-in の方向でいきましょう。

2017-02-08 11:55 UTC, ogihara-ryo commented on app/models/request_application/matcher.rb
>  module RequestApplication::Matcher
このモジュール(モデル)でマッチングの結果を返して
ViewHelper で DOM を作る感じになると思います。明日！

2017-02-09 01:18 UTC, ogihara-ryo commented
殴り書きですが、こんな感じで動きませんか？
テストがあればこんなリファクタに10分もかけることなかったのに。。(愚痴)
全然動かなかったら、sqlite のデータもらえれば見ますー。
```ruby
module RequestApplication::Matcher
  # [
  #   "#{model.code} #{doc_no}" => {
  #     matched: [{ detail: detail, for_matching_data: for_matching_data }, ...],
  #     unmatched_details: [{ detail: detail, unmatched_attributes: [:rev, :mcl] } }, ...],
  #     unmatched_for_matching_datas: [{ for_matching_data: for_matching_data }, ...],
  #   }, ...
  # ]
  def compare_to_matching_datas
    details.group(:doc_no).order(doc_no: :ASC).pluck(:doc_no).map { |doc_no| "#{model.code} #{doc_no}" => compare(doc_no) }
  end

  private

  def compare(doc_no)
    @results = { matched: [], unmatched_details: [], unmatched_for_matching_datas: [] }
    target_details(doc_no).each do |detail|
      unless for_matching_datas(doc_no).all? { |fmd| match?(detail, fmd) }
        @results[:unmatched_details] << { detail: detail, unmatched_attributes: unmatched_attributes(detail, unmatched_for_matching_datas) }
      end
    end
    @results
  end

  def target_details(doc_no)
    details.includes(:doc_type, :chg_type).where(doc_no: doc_no)
  end

  def target_for_matching_datas(doc_no)
    ForMatchingData.where(model_code: model.code, doc_no: doc_no).order(doc_no: :ASC)
  end

  def match?(detail, for_matching_data)
    if detail.compare_attributes == for_matching_data.compare_attributes
      @results[:matched] << { detail: detail, for_matching_data: for_matching_data }
      true
    else
      @results[:unmatched_for_matching_datas] << { for_matching_data: for_matching_data }
      false
    end
  end

  def unmatched_for_matching_datas
    @results[:unmatched_for_matching_datas].map { |h| h[:for_matching_data] }
  end

  def unmatched_attributes(detail, unmatched_for_matching_datas)
    [].tap { |unmatched|
      attributes = detail.compare_attributes
      unmatched_for_matching_datas.select { |fmd| attributes[:doc_no] == fmd[:doc_no] }.map(&:compare_attributes).each do |fmd|
        attributes.keys.select { |key| attributes[key] != for_matching_data[key] }.each { |key| unmatched << key }
      end
    }.uniq
  end

  def replace_diffrent_attribute_value(attributes, unmatched_for_matching_datas)
    same_doc_no_for_matching_datas = unmatched_for_matching_datas.select { |for_matching_data| attributes[:doc_no] == for_matching_data[:doc_no] }.map(&:compare_attributes)
    same_doc_no_for_matching_datas.each do |for_matching_data|
      attributes.keys.select { |key| attributes[key] != for_matching_data[key] }.each do |key|
        attributes[key] = convert_to_display_value(attributes[key])
      end
    end
    attributes
  end
end

module RequestDetail::Matcher
  def compare_attributes
    {
      doc_no: doc_no,
      doc_type: doc_type.name,
      sht: sht,
      rev: rev,
      eo_chgno: eo_chgno,
      chg_type: chg_type&.name,
      mcl: mcl,
      scp_for_smpl: scp_for_smpl,
      scml_ln: scml_ln
    }.map { |key, value| [key, value.to_s] }.to_h
  end
end

module ForMatchingData::Matcher
  def compare_attributes
    {
      doc_no: doc_no,
      doc_type: doc_type_str,
      sht: sht,
      rev: revision,
      eo_chgno: eo_chgno,
      chg_type: chg_type_str,
      mcl: mcl,
      scp_for_smpl: scp_for_smpl,
      scml_ln: scml
    }.map { |key, value| [key, value.to_s] }.to_h
  end
end

module RequestApplicationsHelper
  def link_to_edit_detail_path(name, detail)
    return if name.blank?
    link_to name, edit_request_application_request_detail_path(detail.request_application, detail), class: 'edit-link'
  end

  def render_attributes(model_code, object)
    safe_join(object.compare_attributes.values.delete_if(&:blank?).unshift(model_code), '|')
  end

  def render_unmatched_attributes(model_code, detail, unmatched_attributes)
    safe_join(
      detail.compare_attributes.map { |key, value|
        unmatched_attributes.include?(key) ? render_unmatched_attribute(value) : value
      }, '|'
    )
  end

  def render_unmatched_attribute(value)
    content_tag(:span, value.present? ? value : '？', class: 'unmatch')
  end
end
```

```erb
<tbody>
  <% model_code = @request_application.model.code %>
  <% @matching_results.each do |k, v| %>
    <% v[:matched].each do |value| %>
      <tr>
        <td><%= t('.match') %></td>
        <td><%= k %></td>
        <td><%= link_to_edit_detail_path(render_attributes(model_code, value[:detail]), detail) %></td>
        <td><%= render_attributes(model_code, value[:for_matching_data]) %></td>
      </tr>
    <% end %>

    <% v[:unmatched_details].each do |value| %>
      <tr>
        <td class="unmatch"><%= t('.unmatch') %></td>
        <td><%= k %></td>
        <td><%= link_to_edit_detail_path(render_unmatched_attributes(model_code, value[:detail], value[:render_unmatched_attributes]), detail) %></td>
        <td></td>
      </tr>
    <% end %>

    <% v[:unmatched_for_matching_datas].each do |value| %>
      <tr>
        <td class="unmatch"><%= t('.unmatch') %></td>
        <td><%= k %></td>
        <td></td>
        <td><%= render_attributes(model_code, value[:for_matching_data]) %></td>
      </tr>
    <% end %>
  <% end %>
</tbody>
```

2017-02-09 01:23 UTC, i-yamaguchi commented
ありがとうございます！

>テストがあればこんなリファクタに10分もかけることなかったのに。。(愚痴)

すみません…今度天神来られた時はお昼ごちそうします:sushi:

2017-02-09 05:46 UTC, ogihara-ryo commented on app/models/request_application/matcher.rb
> +    @results[:unmatched_for_matching_datas].uniq!
これ要ります？  `unmatched_attributes` は  `uniq` して返してますが。

2017-02-09 05:49 UTC, ryo-ryukalice requested changes

2017-02-09 05:49 UTC, ogihara-ryo commented on app/models/request_application/matcher.rb
> +  def remove_unnecessary_unmatched_for_matching_datas!
レシーバーや引数で渡したものに対して破壊的変更を行うわけではないので、!は要りません。

2017-02-09 06:56 UTC, i-yamaguchi commented on app/models/request_application/matcher.rb
> +    @results[:unmatched_for_matching_datas].uniq!
ここの部分は
https://github.com/ogis-Yamada-Shizuka/denshow-quick/pull/82/files#diff-558127a68fb3b59a4048c9376f0cdea7R34
L34に処理が流れた際に `要求書詳細` と `K-PEACE` がN:Nで不一致だった場合に、
重複した値が詰まるので `uniq` しています。

2017-02-09 06:59 UTC, i-yamaguchi commented on app/models/request_application/matcher.rb
> +    @results[:unmatched_for_matching_datas].uniq!
`match?` メソッドの方に `if` を挟んだ方が良かったですかね？

```
@results[:unmatched_for_matching_datas] << { for_matching_data: for_matching_data } unless @results[:unmatched_for_matching_datas].includes?( for_matching_data: for_matching_data)
```
こんな感じになるのかな？

2017-02-09 07:08 UTC, ogihara-ryo commented on app/models/request_application/matcher.rb
> +    @results[:unmatched_for_matching_datas].uniq!
いや、このままで ok です！

2017-02-09 07:08 UTC, ryo-ryukalice approved these changes

2017-02-09 07:13 UTC, i-yamaguchi commented
マージしますー

2017-02-09 07:13 UTC, merged

2017-02-09 07:14 UTC, ogihara-ryo commented
#83 rebase お願いしますー