[sp1-02] #TK-01158 リコンサイル結果で一致した情報をCSV出力
ogis-Yamada-Shizuka/denshow-quick pull request #83
Opened 2017-02-08 10:03 UTC by i-yamaguchi

CSV出力ボタンは下記バックログに通りに置いてみましたがちょっと違和感。
```
・リコンサイル結果画面の下部に「K-PEACEインプット用CSVファイル出力」というラベルがある枠を作る。
・枠内に「CSV出力」ボタンを作る
```
戻るリンクをテーブル上部にもってくればもう少しましにはなるかと思います。
![csv](https://cloud.githubusercontent.com/assets/21189471/22732356/3f44adbc-ee31-11e6-9764-2a1390f733ec.png)

2017-02-08 11:41 UTC, i-yamaguchi reviewed
セルフコメント

2017-02-08 11:41 UTC, i-yamaguchi commented on app/models/request_application/matcher_export_csv.rb
> +module RequestApplication::MatcherExportCsv
気になるポイント：
今回のプロジェクトのお作法的にはCSV出力用の `class` を作成して実装しているので、
`request_application` に関連しているとは言えど、お作法的に `module` では無い方が良かった気も。

2017-02-08 11:41 UTC, i-yamaguchi commented on app/models/request_application/matcher_export_csv.rb
> +  HEADER = [
最初は資料の中に項目に対して番号が振られていたので
```
気になるポイント：
HEADER = {
   1 => '種類'
   2 => 'ドキュメント番号'
   .....
}.freeze
```
上記のようにしていたのですが、あまり意味がないかなと思っていまの形に変えました。

2017-02-08 11:41 UTC, i-yamaguchi commented on app/models/request_application/matcher_export_csv.rb
> +      target_for_matching_datas.delete_if do |for_matching_data|
気になるポイント：
理論上複数の `detail` に対して `for_matching_data` が一致することはないので、
`delete_if` にしてますが、そのせいで見づらくなってる気がする。

2017-02-08 11:41 UTC, i-yamaguchi commented on app/models/request_application/matcher_export_csv.rb
> +      values = {}
気になるポイント：
一致していた `detail` と `for_matching_data` から値を `values` に再代入しているところ。

2017-02-08 11:41 UTC, i-yamaguchi commented on app/models/request_application/matcher_export_csv.rb
> +    end.compact
気になるポイント：
不一致だった場合は `values` が空になり、
L72の `values.present? ? values : nil` で `nil` が詰まるので `compact` しているけれど、
そもそも一致した値をぐるぐる回すべき？

2017-02-08 11:41 UTC, i-yamaguchi commented on app/models/request_application/matcher_export_csv.rb
> +  def set_values(values, detail, for_matching_data)
気になるポイント：
メソッド名と、 `detail` などのobjectをそのまま渡しているところ。

2017-02-08 12:02 UTC, ryo-ryukalice requested changes
matcher_export_csv.rb も明日！

2017-02-08 12:02 UTC, ogihara-ryo commented on app/controllers/request_applications/matching_controller.rb
> +        send_data @request_application.export_matching_result_csv, type: 'text/csv; charset=shift_jis', filename: "#{t('file_name.matching_result_export_csv')}_#{Time.zone.now.to_date}.csv"
`ActiveSupport::TimeZone#today` の実装は、 `now.to_date` なので
`Time.zone.today` で OK です。

2017-02-08 12:18 UTC, i-yamaguchi commented on app/controllers/request_applications/matching_controller.rb
> +        send_data @request_application.export_matching_result_csv, type: 'text/csv; charset=shift_jis', filename: "#{t('file_name.matching_result_export_csv')}_#{Time.zone.now.to_date}.csv"
ありがとうございます！
RailsのTime系いろいろなパターンがあって闇を感じる時があるんですが、慣れの問題なんですかね？

2017-02-08 12:21 UTC, ogihara-ryo commented on app/controllers/request_applications/matching_controller.rb
> +        send_data @request_application.export_matching_result_csv, type: 'text/csv; charset=shift_jis', filename: "#{t('file_name.matching_result_export_csv')}_#{Time.zone.now.to_date}.csv"
ActiveSupport は直感的に書けるように頑張っているので、多分慣れの問題ですかねー。
闇を感じるとすれば、国ごとに週の始まりの曜日のスタンダードが違う上、
`wday` , `cwday` , `beginning_of_week` あたりがカオスなとこかな。。

2017-02-08 12:25 UTC, i-yamaguchi commented on app/controllers/request_applications/matching_controller.rb
> +        send_data @request_application.export_matching_result_csv, type: 'text/csv; charset=shift_jis', filename: "#{t('file_name.matching_result_export_csv')}_#{Time.zone.now.to_date}.csv"
>国ごとに週の始まりの曜日のスタンダードが違う上、
>wday , cwday , beginning_of_week あたりがカオスなとこかな。。

これはきついですね…

2017-02-09 07:31 UTC, i-yamaguchi commented
既に荻原さんが `reference` してくれてたみたいですが、developをmergeしてpushしちゃいました。
大丈夫だったかな？

2017-02-09 07:36 UTC, i-yamaguchi commented
あ、変更点は相違ないか確認はしています！

2017-02-09 07:52 UTC, ogihara-ryo commented on app/models/request_application/matcher_export_csv.rb
> +      target_for_matching_datas.delete_if do |for_matching_data|
間違いないですね。修正しましょう。

2017-02-09 10:37 UTC, ogihara-ryo commented on app/models/request_application/matcher_export_csv.rb
> +    target_for_matching_datas = ForMatchingData.where(model_code: model.code).order(doc_no: :ASC)
こんな感じの方が幾分か分かりやすいかな。。
`where` のキャッシュは Ruby でやらなくても多分 Rails がやってくれるはず。
```ruby
def matched_values
  [].tap do |values|
    details.includes(:doc_type, :chg_type).order(doc_no: :ASC).map do |detail|
      ForMatchingData.where(model_code: model.code).order(doc_no: :ASC).each do |for_matching_data|
        if detail.compare_attributes == for_matching_data.compare_attributes
          values << matched_value(detail, for_matching_data)
          break
        end
      end
    end
  end
end

def matched_value(detail, for_matching_data)
  {
    format_type: for_matching_data.format_type,
    document_no: for_matching_data.document_no,
    revision: for_matching_data.revision,
    vendor_code: detail.vendor_code
  }
end
```

2017-02-09 11:47 UTC, ogihara-ryo commented on app/controllers/request_applications/matching_controller.rb
> +        send_data @request_application.export_matching_result_csv, type: 'text/csv; charset=shift_jis', filename: "#{t('file_name.matching_result_export_csv')}_#{Time.zone.now.to_date}.csv"
あとこれ。。

2017-02-10 05:30 UTC, i-yamaguchi commented on app/controllers/request_applications/matching_controller.rb
> +        send_data @request_application.export_matching_result_csv, type: 'text/csv; charset=shift_jis', filename: "#{t('file_name.matching_result_export_csv')}_#{Time.zone.now.to_date}.csv"
すみませんここの修正失念してました:bow:

2017-02-10 05:36 UTC, ryo-ryukalice approved these changes

2017-02-10 05:37 UTC, merged